import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'
import ReduxProvider from './store/ReduxProvider'

export const metadata = {
  title: 'Dine Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}
