import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'
import ReduxProvider from './store/ReduxProvider'
import { ClerkProvider } from "@clerk/nextjs"

export const metadata = {
  title: 'Dine Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ReduxProvider>
            <Header />
            {children}
            <Footer />
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
